Unable to write file 'c:\Users\SYUG\Desktop\Waveplatform\.vscode\extensions.json' (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, mkdir 'c:\Users\SYUG\Desktop\Waveplatform\.vscode')Unable to write file 'c:\Users\SYUG\Desktop\Waveplatform\.vscode\extensions.json' (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, mkdir 'c:\Users\SYUG\Desktop\Waveplatform\.vscode')Unable to write file 'c:\Users\SYUG\Desktop\Waveplatform\.vscode\extensions.json' (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, mkdir 'c:\Users\SYUG\Desktop\Waveplatform\.vscode')Unable to write file 'c:\Users\SYUG\Desktop\Waveplatform\.vscode\extensions.json' (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, mkdir 'c:\Users\SYUG\Desktop\Waveplatform\.vscode')Unable to write file 'c:\Users\SYUG\Desktop\Waveplatform\.vscode\extensions.json' (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, mkdir 'c:\Users\SYUG\Desktop\Waveplatform\.vscode')Unable to write file 'c:\Users\SYUG\Desktop\Waveplatform\.vscode\extensions.json' (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, mkdir 'c:\Users\SYUG\Desktop\Waveplatform\.vscode')Unable to write file 'c:\Users\SYUG\Desktop\Waveplatform\.vscode\extensions.json' (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, mkdir 'c:\Users\SYUG\Desktop\Waveplatform\.vscode')Unable to write file 'c:\Users\SYUG\Desktop\Waveplatform\.vscode\extensions.json' (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, mkdir 'c:\Users\SYUG\Desktop\Waveplatform\.vscode')Unable to write file 'c:\Users\SYUG\Desktop\Waveplatform\.vscode\extensions.json' (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, mkdir 'c:\Users\SYUG\Desktop\Waveplatform\.vscode')const express = require("express");
const engagementController = require("../controllers/engagementController");

const router = express.Router();

router.post("/releases/:releaseId/download", engagementController.trackDownload);
router.post("/releases/:releaseId/listen", engagementController.trackListen);
router.post("/releases/:releaseId/view", engagementController.trackView);

module.exports = router;